name: Code Style Fixer

on:
  [pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare php-cs-fixer
        run: composer global require friendsofphp/php-cs-fixer

      - name: Run php-cs-fixer
        run: export PATH="$PATH:$HOME/.composer/vendor/bin" && php-cs-fixer --config=.php_cs fix src

      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply php-cs-fixer changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_OAUTH_TOKEN }}